export const ZOOM_CHANGE = 'WORKSPACE_ZOOM_CHANGE';

export const DIALOG_SELECT_SCHEMA_TYPE = 'DIALOG_SELECT_SCHEMA_TYPE';
export const DIALOG_SCHEMA_TYPE_SELECTED = 'DIALOG_SCHEMA_TYPE_SELECTED';

export const WORKSPACE_LOAD_RESOURCE = 'WORKSPACE_LOAD_RESOURCE';
export const WORKSPACE_UPDATE_SCHEMAS = 'WORKSPACE_UPDATE_SCHEMAS';
export const WORKSPACE_READY = 'WORKSPACE_READY';
