export const ZOOM_CHANGE = 'WORKSPACE_ZOOM_CHANGE';

export const UPDATE_SCHEMAS = 'UPDATE_SCHEMAS';
export const FILE_ADD_RESOURCE = 'FILE_ADD_RESOURCE';
export const FILE_NEW_RESOURCE = 'FILE_NEW_RESOURCE';
